// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfR-poLoSZ-5bAGdl_SK6HEaRSWOwexa4',
    appId: '1:159509485313:web:322f28cd62ee4c2eabed00',
    messagingSenderId: '159509485313',
    projectId: 'tatbeeqi-7d4a8',
    authDomain: 'tatbeeqi-7d4a8.firebaseapp.com',
    storageBucket: 'tatbeeqi-7d4a8.firebasestorage.app',
    measurementId: 'G-RB6H2YK3FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBXVejYeVQ8UXUBuu3QZg41k0ROeeBbmI',
    appId: '1:159509485313:android:1037d23f4e8f8b7aabed00',
    messagingSenderId: '159509485313',
    projectId: 'tatbeeqi-7d4a8',
    storageBucket: 'tatbeeqi-7d4a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5R8lyySftaEmlJwWsmxniXkhG579Nf4',
    appId: '1:159509485313:ios:2ce6acb829804463abed00',
    messagingSenderId: '159509485313',
    projectId: 'tatbeeqi-7d4a8',
    storageBucket: 'tatbeeqi-7d4a8.firebasestorage.app',
    iosBundleId: 'com.example.tatbeeqi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR5R8lyySftaEmlJwWsmxniXkhG579Nf4',
    appId: '1:159509485313:ios:2ce6acb829804463abed00',
    messagingSenderId: '159509485313',
    projectId: 'tatbeeqi-7d4a8',
    storageBucket: 'tatbeeqi-7d4a8.firebasestorage.app',
    iosBundleId: 'com.example.tatbeeqi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfR-poLoSZ-5bAGdl_SK6HEaRSWOwexa4',
    appId: '1:159509485313:web:e96e063090c7fc5babed00',
    messagingSenderId: '159509485313',
    projectId: 'tatbeeqi-7d4a8',
    authDomain: 'tatbeeqi-7d4a8.firebaseapp.com',
    storageBucket: 'tatbeeqi-7d4a8.firebasestorage.app',
    measurementId: 'G-YJVKB33DSY',
  );
}
