import 'package:flutter/painting.dart';

//
const githubTheme = {
  'root': TextStyle(
    color: Color(0xFF1F2328),
    fontFamily: 'monospace',
    fontSize: 14,
  ),
  'comment': TextStyle(color: Color(0xFF6A737D), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xFF6A737D), fontStyle: FontStyle.italic),
  'keyword': TextStyle(color: Color(0xFFcf222e), fontWeight: FontWeight.bold),
  'selector-tag':
      TextStyle(color: Color(0xFFcf222e), fontWeight: FontWeight.bold),
  'subst': TextStyle(color: Color(0xFF1F2328)),
  'number': TextStyle(color: Color(0xFF0550ae)),
  'literal': TextStyle(color: Color(0xFF0550ae)),
  'string': TextStyle(color: Color(0xFF0a3069)),
  'doctag': TextStyle(color: Color(0xFF0a3069)),
  'variable': TextStyle(color: Color(0xFF953800)),
  'template-variable': TextStyle(color: Color(0xFF953800)),
  'title': TextStyle(color: Color(0xFF0a3069), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xFF0a3069), fontWeight: FontWeight.bold),
  'selector-id':
      TextStyle(color: Color(0xFF0a3069), fontWeight: FontWeight.bold),
  'type': TextStyle(color: Color(0xFF116329), fontWeight: FontWeight.bold),
  'tag': TextStyle(color: Color(0xFF22863a)),
  'name': TextStyle(color: Color(0xFF22863a)),
  'attribute': TextStyle(color: Color(0xFF22863a)),
  'regexp': TextStyle(color: Color(0xFF116329)),
  'link': TextStyle(color: Color(0xFF116329)),
  'symbol': TextStyle(color: Color(0xFF8250df)),
  'bullet': TextStyle(color: Color(0xFF8250df)),
  'built_in': TextStyle(color: Color(0xFF953800)),
  'builtin-name': TextStyle(color: Color(0xFF953800)),
  'meta': TextStyle(color: Color(0xFF57606a)),
  'deletion': TextStyle(color: Color(0xFFffebe9)),
  'addition': TextStyle(color: Color(0xFFdafbe1)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
//
const darkTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff444444), color: Color(0xffdddddd)),
  'keyword': TextStyle(color: Color(0xffffffff), fontWeight: FontWeight.bold),
  'selector-tag':
      TextStyle(color: Color(0xffffffff), fontWeight: FontWeight.bold),
  'literal': TextStyle(color: Color(0xffffffff), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xffffffff), fontWeight: FontWeight.bold),
  'link': TextStyle(color: Color(0xffffffff)),
  'subst': TextStyle(color: Color(0xffdddddd)),
  'string': TextStyle(color: Color(0xffdd8888)),
  'title': TextStyle(color: Color(0xffdd8888), fontWeight: FontWeight.bold),
  'name': TextStyle(color: Color(0xffdd8888), fontWeight: FontWeight.bold),
  'type': TextStyle(color: Color(0xffdd8888), fontWeight: FontWeight.bold),
  'attribute': TextStyle(color: Color(0xffdd8888)),
  'symbol': TextStyle(color: Color(0xffdd8888)),
  'bullet': TextStyle(color: Color(0xffdd8888)),
  'built_in': TextStyle(color: Color(0xffdd8888)),
  'addition': TextStyle(color: Color(0xffdd8888)),
  'variable': TextStyle(color: Color(0xffdd8888)),
  'template-tag': TextStyle(color: Color(0xffdd8888)),
  'template-variable': TextStyle(color: Color(0xffdd8888)),
  'comment': TextStyle(color: Color(0xff777777)),
  'quote': TextStyle(color: Color(0xff777777)),
  'deletion': TextStyle(color: Color(0xff777777)),
  'meta': TextStyle(color: Color(0xff777777)),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
};
//

const defaultTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xffF0F0F0), color: Color(0xff444444)),
  'subst': TextStyle(color: Color(0xff444444)),
  'comment': TextStyle(color: Color(0xff888888)),
  'keyword': TextStyle(fontWeight: FontWeight.bold),
  'attribute': TextStyle(fontWeight: FontWeight.bold),
  'selector-tag': TextStyle(fontWeight: FontWeight.bold),
  'meta-keyword': TextStyle(fontWeight: FontWeight.bold),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'name': TextStyle(fontWeight: FontWeight.bold),
  'type': TextStyle(color: Color(0xff880000)),
  'string': TextStyle(color: Color(0xff880000)),
  'number': TextStyle(color: Color(0xff880000)),
  'selector-id': TextStyle(color: Color(0xff880000)),
  'selector-class': TextStyle(color: Color(0xff880000)),
  'quote': TextStyle(color: Color(0xff880000)),
  'template-tag': TextStyle(color: Color(0xff880000)),
  'deletion': TextStyle(color: Color(0xff880000)),
  'title': TextStyle(color: Color(0xff880000), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xff880000), fontWeight: FontWeight.bold),
  'regexp': TextStyle(color: Color(0xffBC6060)),
  'symbol': TextStyle(color: Color(0xffBC6060)),
  'variable': TextStyle(color: Color(0xffBC6060)),
  'template-variable': TextStyle(color: Color(0xffBC6060)),
  'link': TextStyle(color: Color(0xffBC6060)),
  'selector-attr': TextStyle(color: Color(0xffBC6060)),
  'selector-pseudo': TextStyle(color: Color(0xffBC6060)),
  'literal': TextStyle(color: Color(0xff78A960)),
  'built_in': TextStyle(color: Color(0xff397300)),
  'bullet': TextStyle(color: Color(0xff397300)),
  'code': TextStyle(color: Color(0xff397300)),
  'addition': TextStyle(color: Color(0xff397300)),
  'meta': TextStyle(color: Color(0xff1f7199)),
  'meta-string': TextStyle(color: Color(0xff4d99bf)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
//
const draculaTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff282a36), color: Color(0xfff8f8f2)),
  'keyword': TextStyle(color: Color(0xff8be9fd), fontWeight: FontWeight.bold),
  'selector-tag':
      TextStyle(color: Color(0xff8be9fd), fontWeight: FontWeight.bold),
  'literal': TextStyle(color: Color(0xff8be9fd), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xff8be9fd), fontWeight: FontWeight.bold),
  'link': TextStyle(color: Color(0xff8be9fd)),
  'subst': TextStyle(color: Color(0xfff8f8f2)),
  'string': TextStyle(color: Color(0xfff1fa8c)),
  'title': TextStyle(color: Color(0xfff1fa8c), fontWeight: FontWeight.bold),
  'name': TextStyle(color: Color(0xfff1fa8c), fontWeight: FontWeight.bold),
  'type': TextStyle(color: Color(0xfff1fa8c), fontWeight: FontWeight.bold),
  'attribute': TextStyle(color: Color(0xfff1fa8c)),
  'symbol': TextStyle(color: Color(0xfff1fa8c)),
  'bullet': TextStyle(color: Color(0xfff1fa8c)),
  'addition': TextStyle(color: Color(0xfff1fa8c)),
  'variable': TextStyle(color: Color(0xfff1fa8c)),
  'template-tag': TextStyle(color: Color(0xfff1fa8c)),
  'template-variable': TextStyle(color: Color(0xfff1fa8c)),
  'comment': TextStyle(color: Color(0xff6272a4)),
  'quote': TextStyle(color: Color(0xff6272a4)),
  'deletion': TextStyle(color: Color(0xff6272a4)),
  'meta': TextStyle(color: Color(0xff6272a4)),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
};
//

const googlecodeTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xffffffff), color: Color(0xff000000)),
  'comment': TextStyle(color: Color(0xff880000)),
  'quote': TextStyle(color: Color(0xff880000)),
  'keyword': TextStyle(color: Color(0xff000088)),
  'selector-tag': TextStyle(color: Color(0xff000088)),
  'section': TextStyle(color: Color(0xff000088)),
  'title': TextStyle(color: Color(0xff660066)),
  'name': TextStyle(color: Color(0xff000088)),
  'variable': TextStyle(color: Color(0xff666600)),
  'template-variable': TextStyle(color: Color(0xff666600)),
  'string': TextStyle(color: Color(0xff008800)),
  'selector-attr': TextStyle(color: Color(0xff008800)),
  'selector-pseudo': TextStyle(color: Color(0xff008800)),
  'regexp': TextStyle(color: Color(0xff008800)),
  'literal': TextStyle(color: Color(0xff006666)),
  'symbol': TextStyle(color: Color(0xff006666)),
  'bullet': TextStyle(color: Color(0xff006666)),
  'meta': TextStyle(color: Color(0xff006666)),
  'number': TextStyle(color: Color(0xff006666)),
  'link': TextStyle(color: Color(0xff006666)),
  'doctag': TextStyle(color: Color(0xff660066), fontWeight: FontWeight.bold),
  'type': TextStyle(color: Color(0xff660066)),
  'attr': TextStyle(color: Color(0xff660066)),
  'built_in': TextStyle(color: Color(0xff660066)),
  'builtin-name': TextStyle(color: Color(0xff660066)),
  'params': TextStyle(color: Color(0xff660066)),
  'attribute': TextStyle(color: Color(0xff000000)),
  'subst': TextStyle(color: Color(0xff000000)),
  'formula': TextStyle(
      backgroundColor: Color(0xffeeeeee), fontStyle: FontStyle.italic),
  'selector-id': TextStyle(color: Color(0xff9B703F)),
  'selector-class': TextStyle(color: Color(0xff9B703F)),
  'addition': TextStyle(backgroundColor: Color(0xffbaeeba)),
  'deletion': TextStyle(backgroundColor: Color(0xffffc8bd)),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
};
//

const gradientDarkTheme = {
  'root': TextStyle(color: Color(0xffe7e4eb)),
  'subtr': TextStyle(color: Color(0xffe7e4eb)),
  'doctag': TextStyle(color: Color(0xffaf8dd9)),
  'meta': TextStyle(color: Color(0xffaf8dd9)),
  'comment': TextStyle(color: Color(0xffaf8dd9)),
  'quote': TextStyle(color: Color(0xffaf8dd9), fontStyle: FontStyle.italic),
  'selector-tag':
      TextStyle(color: Color(0xffAEFBFF), fontWeight: FontWeight.bold),
  'selector-id':
      TextStyle(color: Color(0xffAEFBFF), fontWeight: FontWeight.bold),
  'template-tag':
      TextStyle(color: Color(0xffAEFBFF), fontWeight: FontWeight.bold),
  'regexp': TextStyle(color: Color(0xffAEFBFF)),
  'attr': TextStyle(color: Color(0xffAEFBFF)),
  'tag': TextStyle(color: Color(0xffAEFBFF)),
  'params': TextStyle(color: Color(0xffF19FFF), fontWeight: FontWeight.bold),
  'selector-class':
      TextStyle(color: Color(0xffF19FFF), fontWeight: FontWeight.bold),
  'bullet': TextStyle(color: Color(0xffF19FFF)),
  'keyword': TextStyle(color: Color(0xff17fc95), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xff17fc95), fontWeight: FontWeight.bold),
  'meta-keyword': TextStyle(color: Color(0xff17fc95)),
  'symbol': TextStyle(color: Color(0xff17fc95)),
  'type': TextStyle(color: Color(0xff17fc95)),
  'addition': TextStyle(color: Color(0xffE7FF9F)),
  'number': TextStyle(color: Color(0xffC5FE00)),
  'link': TextStyle(color: Color(0xffC5FE00)),
  'string': TextStyle(color: Color(0xff38c0ff)),
  'attribute': TextStyle(color: Color(0xffE7FF9F)),
  'variable': TextStyle(color: Color(0xffE447FF)),
  'template-variable': TextStyle(color: Color(0xffE447FF)),
  'builtin-name': TextStyle(color: Color(0xffFFC800)),
  'built_in': TextStyle(color: Color(0xffFFC800)),
  'formula': TextStyle(color: Color(0xffFFC800)),
  'name': TextStyle(color: Color(0xffFFC800)),
  'title': TextStyle(color: Color(0xffFFC800)),
  'class': TextStyle(color: Color(0xffFFC800)),
  'function': TextStyle(color: Color(0xffFFC800)),
  'selector-pseudo': TextStyle(color: Color(0xffFF9E44)),
  'deletion': TextStyle(color: Color(0xffFF9E44)),
  'literal': TextStyle(color: Color(0xffFF9E44)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
//
const monoBlueTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xffeaeef3), color: Color(0xff00193a)),
  'keyword': TextStyle(fontWeight: FontWeight.bold),
  'selector-tag': TextStyle(fontWeight: FontWeight.bold),
  'title': TextStyle(fontWeight: FontWeight.bold, color: Color(0xff0048ab)),
  'section': TextStyle(fontWeight: FontWeight.bold, color: Color(0xff0048ab)),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'name': TextStyle(fontWeight: FontWeight.bold, color: Color(0xff0048ab)),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'comment': TextStyle(color: Color(0xff738191)),
  'string': TextStyle(color: Color(0xff0048ab)),
  'built_in': TextStyle(color: Color(0xff0048ab)),
  'literal': TextStyle(color: Color(0xff0048ab)),
  'type': TextStyle(color: Color(0xff0048ab)),
  'addition': TextStyle(color: Color(0xff0048ab)),
  'tag': TextStyle(color: Color(0xff0048ab)),
  'quote': TextStyle(color: Color(0xff0048ab)),
  'selector-id': TextStyle(color: Color(0xff0048ab)),
  'selector-class': TextStyle(color: Color(0xff0048ab)),
  'meta': TextStyle(color: Color(0xff4c81c9)),
  'subst': TextStyle(color: Color(0xff4c81c9)),
  'symbol': TextStyle(color: Color(0xff4c81c9)),
  'regexp': TextStyle(color: Color(0xff4c81c9)),
  'attribute': TextStyle(color: Color(0xff4c81c9)),
  'deletion': TextStyle(color: Color(0xff4c81c9)),
  'variable': TextStyle(color: Color(0xff4c81c9)),
  'template-variable': TextStyle(color: Color(0xff4c81c9)),
  'link': TextStyle(color: Color(0xff4c81c9)),
  'bullet': TextStyle(color: Color(0xff4c81c9)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
};
//

const monokaiTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff272822), color: Color(0xffdddddd)),
  'tag': TextStyle(color: Color(0xfff92672)),
  'keyword': TextStyle(color: Color(0xfff92672), fontWeight: FontWeight.bold),
  'selector-tag':
      TextStyle(color: Color(0xfff92672), fontWeight: FontWeight.bold),
  'literal': TextStyle(color: Color(0xfff92672), fontWeight: FontWeight.bold),
  'strong': TextStyle(color: Color(0xfff92672)),
  'name': TextStyle(color: Color(0xfff92672)),
  'code': TextStyle(color: Color(0xff66d9ef)),
  'attribute': TextStyle(color: Color(0xffbf79db)),
  'symbol': TextStyle(color: Color(0xffbf79db)),
  'regexp': TextStyle(color: Color(0xffbf79db)),
  'link': TextStyle(color: Color(0xffbf79db)),
  'string': TextStyle(color: Color(0xffa6e22e)),
  'bullet': TextStyle(color: Color(0xffa6e22e)),
  'subst': TextStyle(color: Color(0xffa6e22e)),
  'title': TextStyle(color: Color(0xffa6e22e), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xffa6e22e), fontWeight: FontWeight.bold),
  'emphasis': TextStyle(color: Color(0xffa6e22e)),
  'type': TextStyle(color: Color(0xffa6e22e), fontWeight: FontWeight.bold),
  'built_in': TextStyle(color: Color(0xffa6e22e)),
  'builtin-name': TextStyle(color: Color(0xffa6e22e)),
  'selector-attr': TextStyle(color: Color(0xffa6e22e)),
  'selector-pseudo': TextStyle(color: Color(0xffa6e22e)),
  'addition': TextStyle(color: Color(0xffa6e22e)),
  'variable': TextStyle(color: Color(0xffa6e22e)),
  'template-tag': TextStyle(color: Color(0xffa6e22e)),
  'template-variable': TextStyle(color: Color(0xffa6e22e)),
  'comment': TextStyle(color: Color(0xff75715e)),
  'quote': TextStyle(color: Color(0xff75715e)),
  'deletion': TextStyle(color: Color(0xff75715e)),
  'meta': TextStyle(color: Color(0xff75715e)),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'selector-id': TextStyle(fontWeight: FontWeight.bold),
};
//

const tomorrowNightBlueTheme = {
  'comment': TextStyle(color: Color(0xff7285b7)),
  'quote': TextStyle(color: Color(0xff7285b7)),
  'variable': TextStyle(color: Color(0xffff9da4)),
  'template-variable': TextStyle(color: Color(0xffff9da4)),
  'tag': TextStyle(color: Color(0xffff9da4)),
  'name': TextStyle(color: Color(0xffff9da4)),
  'selector-id': TextStyle(color: Color(0xffff9da4)),
  'selector-class': TextStyle(color: Color(0xffff9da4)),
  'regexp': TextStyle(color: Color(0xffff9da4)),
  'deletion': TextStyle(color: Color(0xffff9da4)),
  'number': TextStyle(color: Color(0xffffc58f)),
  'built_in': TextStyle(color: Color(0xffffc58f)),
  'builtin-name': TextStyle(color: Color(0xffffc58f)),
  'literal': TextStyle(color: Color(0xffffc58f)),
  'type': TextStyle(color: Color(0xffffc58f)),
  'params': TextStyle(color: Color(0xffffc58f)),
  'meta': TextStyle(color: Color(0xffffc58f)),
  'link': TextStyle(color: Color(0xffffc58f)),
  'attribute': TextStyle(color: Color(0xffffeead)),
  'string': TextStyle(color: Color(0xffd1f1a9)),
  'symbol': TextStyle(color: Color(0xffd1f1a9)),
  'bullet': TextStyle(color: Color(0xffd1f1a9)),
  'addition': TextStyle(color: Color(0xffd1f1a9)),
  'title': TextStyle(color: Color(0xffbbdaff)),
  'section': TextStyle(color: Color(0xffbbdaff)),
  'keyword': TextStyle(color: Color(0xffebbbff)),
  'selector-tag': TextStyle(color: Color(0xffebbbff)),
  'root':
      TextStyle(backgroundColor: Color(0xff002451), color: Color(0xffffffff)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
//

const a11yDarkTheme = {
  'comment': TextStyle(color: Color(0xffd4d0ab)),
  'quote': TextStyle(color: Color(0xffd4d0ab)),
  'variable': TextStyle(color: Color(0xffffa07a)),
  'template-variable': TextStyle(color: Color(0xffffa07a)),
  'tag': TextStyle(color: Color(0xffffa07a)),
  'name': TextStyle(color: Color(0xffffa07a)),
  'selector-id': TextStyle(color: Color(0xffffa07a)),
  'selector-class': TextStyle(color: Color(0xffffa07a)),
  'regexp': TextStyle(color: Color(0xffffa07a)),
  'deletion': TextStyle(color: Color(0xffffa07a)),
  'number': TextStyle(color: Color(0xfff5ab35)),
  'built_in': TextStyle(color: Color(0xfff5ab35)),
  'builtin-name': TextStyle(color: Color(0xfff5ab35)),
  'literal': TextStyle(color: Color(0xfff5ab35)),
  'type': TextStyle(color: Color(0xfff5ab35)),
  'params': TextStyle(color: Color(0xfff5ab35)),
  'meta': TextStyle(color: Color(0xfff5ab35)),
  'link': TextStyle(color: Color(0xfff5ab35)),
  'attribute': TextStyle(color: Color(0xffffd700)),
  'string': TextStyle(color: Color(0xffabe338)),
  'symbol': TextStyle(color: Color(0xffabe338)),
  'bullet': TextStyle(color: Color(0xffabe338)),
  'addition': TextStyle(color: Color(0xffabe338)),
  'title': TextStyle(color: Color(0xff00e0e0)),
  'section': TextStyle(color: Color(0xff00e0e0)),
  'keyword': TextStyle(color: Color(0xffdcc6e0)),
  'selector-tag': TextStyle(color: Color(0xffdcc6e0)),
  'root':
      TextStyle(backgroundColor: Color(0xff2b2b2b), color: Color(0xfff8f8f2)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
//

const a11yLightTheme = {
  'comment': TextStyle(color: Color(0xff696969)),
  'quote': TextStyle(color: Color(0xff696969)),
  'variable': TextStyle(color: Color(0xffd91e18)),
  'template-variable': TextStyle(color: Color(0xffd91e18)),
  'tag': TextStyle(color: Color(0xffd91e18)),
  'name': TextStyle(color: Color(0xffd91e18)),
  'selector-id': TextStyle(color: Color(0xffd91e18)),
  'selector-class': TextStyle(color: Color(0xffd91e18)),
  'regexp': TextStyle(color: Color(0xffd91e18)),
  'deletion': TextStyle(color: Color(0xffd91e18)),
  'number': TextStyle(color: Color(0xffaa5d00)),
  'built_in': TextStyle(color: Color(0xffaa5d00)),
  'builtin-name': TextStyle(color: Color(0xffaa5d00)),
  'literal': TextStyle(color: Color(0xffaa5d00)),
  'type': TextStyle(color: Color(0xffaa5d00)),
  'params': TextStyle(color: Color(0xffaa5d00)),
  'meta': TextStyle(color: Color(0xffaa5d00)),
  'link': TextStyle(color: Color(0xffaa5d00)),
  'attribute': TextStyle(color: Color(0xffaa5d00)),
  'string': TextStyle(color: Color(0xff008000)),
  'symbol': TextStyle(color: Color(0xff008000)),
  'bullet': TextStyle(color: Color(0xff008000)),
  'addition': TextStyle(color: Color(0xff008000)),
  'title': TextStyle(color: Color(0xff007faa)),
  'section': TextStyle(color: Color(0xff007faa)),
  'keyword': TextStyle(color: Color(0xff7928a1)),
  'selector-tag': TextStyle(color: Color(0xff7928a1)),
  'root':
      TextStyle(backgroundColor: Color(0xFFF5F5F5), color: Color(0xff545454)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
//

const atelierCaveDarkTheme = {
  'comment': TextStyle(color: Color(0xff7e7887)),
  'quote': TextStyle(color: Color(0xff7e7887)),
  'variable': TextStyle(color: Color(0xffbe4678)),
  'template-variable': TextStyle(color: Color(0xffbe4678)),
  'attribute': TextStyle(color: Color(0xffbe4678)),
  'regexp': TextStyle(color: Color(0xffbe4678)),
  'link': TextStyle(color: Color(0xffbe4678)),
  'tag': TextStyle(color: Color(0xffbe4678)),
  'name': TextStyle(color: Color(0xffbe4678)),
  'selector-id': TextStyle(color: Color(0xffbe4678)),
  'selector-class': TextStyle(color: Color(0xffbe4678)),
  'number': TextStyle(color: Color(0xffaa573c)),
  'meta': TextStyle(color: Color(0xffaa573c)),
  'built_in': TextStyle(color: Color(0xffaa573c)),
  'builtin-name': TextStyle(color: Color(0xffaa573c)),
  'literal': TextStyle(color: Color(0xffaa573c)),
  'type': TextStyle(color: Color(0xffaa573c)),
  'params': TextStyle(color: Color(0xffaa573c)),
  'string': TextStyle(color: Color(0xff2a9292)),
  'symbol': TextStyle(color: Color(0xff2a9292)),
  'bullet': TextStyle(color: Color(0xff2a9292)),
  'title': TextStyle(color: Color(0xff576ddb)),
  'section': TextStyle(color: Color(0xff576ddb)),
  'keyword': TextStyle(color: Color(0xff955ae7)),
  'selector-tag': TextStyle(color: Color(0xff955ae7)),
  'deletion':
      TextStyle(color: Color(0xff19171c), backgroundColor: Color(0xffbe4678)),
  'addition':
      TextStyle(color: Color(0xff19171c), backgroundColor: Color(0xff2a9292)),
  'root':
      TextStyle(backgroundColor: Color(0xff19171c), color: Color(0xff8b8792)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
//

const atelierCaveLightTheme = {
  'comment': TextStyle(color: Color(0xff655f6d)),
  'quote': TextStyle(color: Color(0xff655f6d)),
  'variable': TextStyle(color: Color(0xffbe4678)),
  'template-variable': TextStyle(color: Color(0xffbe4678)),
  'attribute': TextStyle(color: Color(0xffbe4678)),
  'tag': TextStyle(color: Color(0xffbe4678)),
  'name': TextStyle(color: Color(0xffbe4678)),
  'regexp': TextStyle(color: Color(0xffbe4678)),
  'link': TextStyle(color: Color(0xffbe4678)),
  'selector-id': TextStyle(color: Color(0xffbe4678)),
  'selector-class': TextStyle(color: Color(0xffbe4678)),
  'number': TextStyle(color: Color(0xffaa573c)),
  'meta': TextStyle(color: Color(0xffaa573c)),
  'built_in': TextStyle(color: Color(0xffaa573c)),
  'builtin-name': TextStyle(color: Color(0xffaa573c)),
  'literal': TextStyle(color: Color(0xffaa573c)),
  'type': TextStyle(color: Color(0xffaa573c)),
  'params': TextStyle(color: Color(0xffaa573c)),
  'string': TextStyle(color: Color(0xff2a9292)),
  'symbol': TextStyle(color: Color(0xff2a9292)),
  'bullet': TextStyle(color: Color(0xff2a9292)),
  'title': TextStyle(color: Color(0xff576ddb)),
  'section': TextStyle(color: Color(0xff576ddb)),
  'keyword': TextStyle(color: Color(0xff955ae7)),
  'selector-tag': TextStyle(color: Color(0xff955ae7)),
  'deletion':
      TextStyle(color: Color(0xff19171c), backgroundColor: Color(0xffbe4678)),
  'addition':
      TextStyle(color: Color(0xff19171c), backgroundColor: Color(0xff2a9292)),
  'root':
      TextStyle(backgroundColor: Color(0xffefecf4), color: Color(0xff585260)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
//
